name: Automatically Deployment // workflow를 실행시키기 위한 event 명

on: [push] // workflow를 실행시킬 브런치와 요청(push, pull request)

jobs: // workflow의 job목록
deployment: //job name
 runs-on: ubuntu-latest // runner가 실행되는 환경
 steps:
  - uses: actions/checkout@v3  //해당 레포지토리로 check-out하여 레포지토리에 접근할 수 있는 Action 불러오기 
  - uses: actions/setup-node@v3 //사용할 node 버전 (node 16 부터는 node@v3)
    with:
      node-version: '16'
    // 실행될 명령에 대한 설명 
  - name: Setting .env
    run: | // workflow 명령
       echo "REACT_APP_MY_NAVER_CLIENT_ID =$REACT_APP_MY_NAVER_CLIENT_ID" >> .env
       echo "REACT_APP_MY_NAVER_CLIENT_SECRET =$REACT_APP_MY_NAVER_CLIENT_SECRET" >> .env
       echo "REACT_APP_MY_POWERBI_ID =$REACT_APP_MY_POWERBI_ID" >> .env
       echo "REACT_APP_MY_POWERBI_ID_URL =$REACT_APP_MY_POWERBI_ID_URL" >> .env
       echo "REACT_APP_MY_POWERBI_TOKEN =$REACT_APP_MY_POWERBI_TOKEN" >> .env
       // echo: 콘솔 창에 인수로 방은 문자열을 출력하는 명령어
       // >> : 출력 받은 문자열을 파일에 저장하는 명령어
    env:  
     REACT_APP_MY_NAVER_CLIENT_ID: ${{secrets.REACT_APP_MY_NAVER_CLIENT_ID}}
     REACT_APP_MY_NAVER_CLIENT_SECRET: ${{secrets.REACT_APP_MY_NAVER_CLIENT_SECRET}}
     REACT_APP_MY_POWERBI_ID: ${{secrets.REACT_APP_MY_POWERBI_ID}}
     REACT_APP_MY_POWERBI_ID_URL: ${{secrets.REACT_APP_MY_POWERBI_ID_URL}}
     REACT_APP_MY_POWERBI_TOKEN: ${{secrets.REACT_APP_MY_POWERBI_TOKEN}}
